### ISSUE TITLE
appeal discord ban

### ISSUE THREAD

**Issue by rekitrelt** [Mauler125/detours_r5#59]
my discord token got stolen, I changed my password on my phone so no one has access to it except me now but I got banned from R5Reloaded because he posted an invite to his scam server I would like to ask to be unbanned because that wasnt me who did that and I want to download and contribute to the mods

**Comment by GreasyMoo** [comment]
discord ban appeal
I have not used r5reloaded in upwards of 6 months because it was kinda garbo, however this saturday i foolishly made the decision to post gay black pornography in the #media channel. I wholeheartedly apologize for my actions and make a humble request to be reallowed into theR5reloaded discord server once more.

**Comment by GreasyMoo** [comment]
discord ban appeal
I have not used r5reloaded in upwards of 6 months because it was kinda garbo, however this saturday i foolishly made the decision to post gay black pornography in the #media channel. I wholeheartedly apologize for my actions and make a humble request to be reallowed into theR5reloaded discord server once more.
